auto_reload_config 0.1

# BEGIN_KITTY_THEME
# Gruvbox Material Dark Hard
include current-theme.conf
# END_KITTY_THEME
font_family MonoLisa
font_size 13.0

background_opacity 0.9
dynamic_background_opacity yes
background #0B0A0E
foreground #EEE8DA

selection_background #2A2118
selection_foreground #EEE8DA

cursor #d8a657
cursor_text_color #0B0A0E

active_border_color #d8a657
inactive_border_color #504945
# Use the splits layout first
enabled_layouts splits:split_axis=auto;equalize_on_close=true,tall,stack

# Create Kitty splits
map ctrl+alt+enter launch --location=split --cwd=current
map ctrl+alt+v launch --location=vsplit --cwd=current
map ctrl+alt+s launch --location=hsplit --cwd=current

# Move between Kitty splits
map ctrl+alt+h neighboring_window left
map ctrl+alt+j neighboring_window down
map ctrl+alt+k neighboring_window up
map ctrl+alt+l neighboring_window right

# Resize Kitty splits
map ctrl+alt+shift+h resize_window narrower
map ctrl+alt+shift+l resize_window wider
map ctrl+alt+shift+j resize_window shorter
map ctrl+alt+shift+k resize_window taller

# Fix/equalize layout
map ctrl+alt+e layout_action equalize
map ctrl+alt+r layout_action rotate
map ctrl+alt+z toggle_layout stack
